apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-app-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: sentiment-app
  template:
    metadata:
      labels:
        app: sentiment-app
      annotations:
        prometheus.io/scrape: 'true' 
        prometheus.io/port: '8080'   
    spec:
      containers:
      - name: sentiment-analysis-container
        image: ravijpatel/sentiment-analysis:latest 
        ports:
        - containerPort: 8080