apiVersion: v1
kind: Service
metadata:
  name: sentiment-app-service
spec:
  selector:
    app: sentiment-app
  type: NodePort # Exposes the service on each Node's IP at a static port
  ports:
    - protocol: TCP
      port: 8080       # Port on the service
      targetPort: 8080 # Port on the pod