apiVersion: v1
kind: Service
metadata:
  name: sentiment-app-service
spec:
  selector:
    app: sentiment-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080       
      targetPort: 8080 